version: '3'

services:
    api:
        container_name: api
        build: 
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        env_file: .env
        volumes:
            - .:/app
        ports:
            - '${PORT}:${PORT}'